// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod congee_flat {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_NODE_TYPE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_NODE_TYPE: u8 = 7;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_NODE_TYPE: [NodeType; 8] = [
  NodeType::N4_INTERNAL,
  NodeType::N16_INTERNAL,
  NodeType::N48_INTERNAL,
  NodeType::N256_INTERNAL,
  NodeType::N4_LEAF,
  NodeType::N16_LEAF,
  NodeType::N48_LEAF,
  NodeType::N256_LEAF,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct NodeType(pub u8);
#[allow(non_upper_case_globals)]
impl NodeType {
  pub const N4_INTERNAL: Self = Self(0);
  pub const N16_INTERNAL: Self = Self(1);
  pub const N48_INTERNAL: Self = Self(2);
  pub const N256_INTERNAL: Self = Self(3);
  pub const N4_LEAF: Self = Self(4);
  pub const N16_LEAF: Self = Self(5);
  pub const N48_LEAF: Self = Self(6);
  pub const N256_LEAF: Self = Self(7);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 7;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::N4_INTERNAL,
    Self::N16_INTERNAL,
    Self::N48_INTERNAL,
    Self::N256_INTERNAL,
    Self::N4_LEAF,
    Self::N16_LEAF,
    Self::N48_LEAF,
    Self::N256_LEAF,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::N4_INTERNAL => Some("N4_INTERNAL"),
      Self::N16_INTERNAL => Some("N16_INTERNAL"),
      Self::N48_INTERNAL => Some("N48_INTERNAL"),
      Self::N256_INTERNAL => Some("N256_INTERNAL"),
      Self::N4_LEAF => Some("N4_LEAF"),
      Self::N16_LEAF => Some("N16_LEAF"),
      Self::N48_LEAF => Some("N48_LEAF"),
      Self::N256_LEAF => Some("N256_LEAF"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for NodeType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for NodeType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for NodeType {
    type Output = NodeType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for NodeType {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for NodeType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for NodeType {}
// struct Child, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Child(pub [u8; 8]);
impl Default for Child { 
  fn default() -> Self { 
    Self([0; 8])
  }
}
impl core::fmt::Debug for Child {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Child")
      .field("key", &self.key())
      .field("node_index", &self.node_index())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Child {}
impl<'a> flatbuffers::Follow<'a> for Child {
  type Inner = &'a Child;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Child>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Child {
  type Inner = &'a Child;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Child>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Child {
    type Output = Child;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const Child as *const u8, Self::size());
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for Child {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Child {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    key: u8,
    node_index: u32,
  ) -> Self {
    let mut s = Self([0; 8]);
    s.set_key(key);
    s.set_node_index(node_index);
    s
  }

  pub fn key(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<<u8 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_key(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn node_index(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<<u32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_node_index(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum CongeeFlatOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CongeeFlat<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for CongeeFlat<'a> {
  type Inner = CongeeFlat<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> CongeeFlat<'a> {
  pub const VT_NODE_TYPES: flatbuffers::VOffsetT = 4;
  pub const VT_PREFIX_BYTES: flatbuffers::VOffsetT = 6;
  pub const VT_PREFIX_OFFSETS: flatbuffers::VOffsetT = 8;
  pub const VT_CHILDREN_DATA: flatbuffers::VOffsetT = 10;
  pub const VT_CHILDREN_OFFSETS: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    CongeeFlat { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args CongeeFlatArgs<'args>
  ) -> flatbuffers::WIPOffset<CongeeFlat<'bldr>> {
    let mut builder = CongeeFlatBuilder::new(_fbb);
    if let Some(x) = args.children_offsets { builder.add_children_offsets(x); }
    if let Some(x) = args.children_data { builder.add_children_data(x); }
    if let Some(x) = args.prefix_offsets { builder.add_prefix_offsets(x); }
    if let Some(x) = args.prefix_bytes { builder.add_prefix_bytes(x); }
    if let Some(x) = args.node_types { builder.add_node_types(x); }
    builder.finish()
  }


  #[inline]
  pub fn node_types(&self) -> Option<flatbuffers::Vector<'a, NodeType>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, NodeType>>>(CongeeFlat::VT_NODE_TYPES, None)}
  }
  #[inline]
  pub fn prefix_bytes(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(CongeeFlat::VT_PREFIX_BYTES, None)}
  }
  #[inline]
  pub fn prefix_offsets(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(CongeeFlat::VT_PREFIX_OFFSETS, None)}
  }
  #[inline]
  pub fn children_data(&self) -> Option<flatbuffers::Vector<'a, Child>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Child>>>(CongeeFlat::VT_CHILDREN_DATA, None)}
  }
  #[inline]
  pub fn children_offsets(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(CongeeFlat::VT_CHILDREN_OFFSETS, None)}
  }
}

impl flatbuffers::Verifiable for CongeeFlat<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, NodeType>>>("node_types", Self::VT_NODE_TYPES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("prefix_bytes", Self::VT_PREFIX_BYTES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("prefix_offsets", Self::VT_PREFIX_OFFSETS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Child>>>("children_data", Self::VT_CHILDREN_DATA, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("children_offsets", Self::VT_CHILDREN_OFFSETS, false)?
     .finish();
    Ok(())
  }
}
pub struct CongeeFlatArgs<'a> {
    pub node_types: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, NodeType>>>,
    pub prefix_bytes: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub prefix_offsets: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub children_data: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Child>>>,
    pub children_offsets: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
}
impl<'a> Default for CongeeFlatArgs<'a> {
  #[inline]
  fn default() -> Self {
    CongeeFlatArgs {
      node_types: None,
      prefix_bytes: None,
      prefix_offsets: None,
      children_data: None,
      children_offsets: None,
    }
  }
}

pub struct CongeeFlatBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> CongeeFlatBuilder<'a, 'b> {
  #[inline]
  pub fn add_node_types(&mut self, node_types: flatbuffers::WIPOffset<flatbuffers::Vector<'b , NodeType>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CongeeFlat::VT_NODE_TYPES, node_types);
  }
  #[inline]
  pub fn add_prefix_bytes(&mut self, prefix_bytes: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CongeeFlat::VT_PREFIX_BYTES, prefix_bytes);
  }
  #[inline]
  pub fn add_prefix_offsets(&mut self, prefix_offsets: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CongeeFlat::VT_PREFIX_OFFSETS, prefix_offsets);
  }
  #[inline]
  pub fn add_children_data(&mut self, children_data: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Child>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CongeeFlat::VT_CHILDREN_DATA, children_data);
  }
  #[inline]
  pub fn add_children_offsets(&mut self, children_offsets: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(CongeeFlat::VT_CHILDREN_OFFSETS, children_offsets);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> CongeeFlatBuilder<'a, 'b> {
    let start = _fbb.start_table();
    CongeeFlatBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<CongeeFlat<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for CongeeFlat<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("CongeeFlat");
      ds.field("node_types", &self.node_types());
      ds.field("prefix_bytes", &self.prefix_bytes());
      ds.field("prefix_offsets", &self.prefix_offsets());
      ds.field("children_data", &self.children_data());
      ds.field("children_offsets", &self.children_offsets());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `CongeeFlat`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_congee_flat_unchecked`.
pub fn root_as_congee_flat(buf: &[u8]) -> Result<CongeeFlat, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<CongeeFlat>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `CongeeFlat` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_congee_flat_unchecked`.
pub fn size_prefixed_root_as_congee_flat(buf: &[u8]) -> Result<CongeeFlat, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<CongeeFlat>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `CongeeFlat` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_congee_flat_unchecked`.
pub fn root_as_congee_flat_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<CongeeFlat<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<CongeeFlat<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `CongeeFlat` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_congee_flat_unchecked`.
pub fn size_prefixed_root_as_congee_flat_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<CongeeFlat<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<CongeeFlat<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a CongeeFlat and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `CongeeFlat`.
pub unsafe fn root_as_congee_flat_unchecked(buf: &[u8]) -> CongeeFlat {
  flatbuffers::root_unchecked::<CongeeFlat>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed CongeeFlat and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `CongeeFlat`.
pub unsafe fn size_prefixed_root_as_congee_flat_unchecked(buf: &[u8]) -> CongeeFlat {
  flatbuffers::size_prefixed_root_unchecked::<CongeeFlat>(buf)
}
#[inline]
pub fn finish_congee_flat_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<CongeeFlat<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_congee_flat_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<CongeeFlat<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod CongeeFlat

